name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-dev

      - name: Update plugin version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          sed -i "s/Version: .*/Version: $TAG_NAME/" PantheonSecretsExplorer.php

      - name: Create release archive
        run: zip -r pantheon-secrets-explorer.zip . -x "*.git*"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.zip
